### ISSUE TITLE
How to improve the algorithm?

### ISSUE THREAD

**Issue by fernandoGuisso** [ivanseidel/IAMDinosaur#12]
How it work, how can i improve the algorithm, learner.js, i need to study genome mutation?
Where i find more docs about this kind of programming?

**Comment by ivanseidel** [comment]
Hi @fernandoGuisso , you will find lots of resources on the Internet about Genetic Algorithms, Neural Networks and so on.

There isn't a perfect place to look for it, just Google ;)
