### ISSUE TITLE
After 235 generation it still not pass the single cactus

### ISSUE THREAD

**Issue by ziaontech** [ivanseidel/IAMDinosaur#14]
While running it on Linux Ubuntu even after 235 generation it still not able to pass the single cactus

**Comment by ivanseidel** [comment]
Hi @ziaontech 

Please, check if the following is happening:

* The "Distance" is always 0, or, the distance becomes 0 when the dinosaur is "down"
* The sensors (while playing manually, without running the algorithm) are correct
* The sensors are being updated in real time (at least 10 times a second)
* The fitness is being counted correctly (each close cactus from the dinosaur, +1)

If anything else you see, please let me know.

**Comment by alchemi5t** [comment]
Why does the distance go to 0 when the dino is down?
After 25 gen the distance sensor gets glitchy.why?

**Comment by alchemi5t** [comment]
Also the fitness keeps incrementing after every jump.this happens after quite some generations.

**Comment by ivanseidel** [comment]
Hi @alchemi5t, take a look at this known bug:
https://github.com/ivanseidel/IAMDinosaur#be-aware-of-a-game-bug
