### ISSUE TITLE
Dark Mode Not Working

### ISSUE THREAD

**Issue by charlestruluck** [ivanseidel/IAMDinosaur#39]
When the game enters dark mode, and starts rotating between light and dark mode, the AI does not realize all the colors just swapped so it doesn't know to keep learning or even to click to restart the game. Is there a fix it this? Thanks.

**Comment by lesander** [comment]
@charlestruluck Please see my answer in issue #24.

**Comment by charlestruluck** [comment]
Thanks, got it.
