### ISSUE TITLE
Do not work when the sky turns black

### ISSUE THREAD

**Issue by trunghai95** [ivanseidel/IAMDinosaur#44]
When the game reach 700 points the colors of the game change: sky turns black (#000000) and objects turn grey (#ACACAC). I've read the GameManipulator.js code and it clearly does not handle that case and the game will be over right after that. How can you manage to get over 2k points with that problem not fixed yet?

**Comment by wblondel** [comment]
The code was written in 2015, and night mode appeared in 2016.
