### ISSUE TITLE
BUG NOITE

### ISSUE THREAD

**Issue by wellingtomwsn** [ivanseidel/IAMDinosaur#49]
Tem algo em mente de como resolver o bug quando chega de noite no game? porque ele não passa de lá! alguma solução?

**Comment by joaopedrovbs** [comment]
E aí cara beleza? Não é um BUG, a parte da noite foi inserida depois de quando o sistema foi programado, o que nos falta é o tempo pra sentar e reprogramar ele pra funcionar, se você tiver esse tempo, pode mandar ver e construir essa função!!

**Comment by wellingtomwsn** [comment]
OK, Amigo, muito obrigado pela atenção, rolando o  tópicos vi que colocando este código no SOUCE do chrome '' Runner.config.INVERT_DISTANCE = Infinity ''   resolve...

**Comment by wellingtomwsn** [comment]
OK, Amigo, muito obrigado pela atenção, rolando o tópicos vi que colocando este código no SOUCE do chrome '' Runner.config.INVERT_DISTANCE = Infinity '' resolve...
