### ISSUE TITLE
Game wont refresh

### ISSUE THREAD

**Issue by GritPixel** [ivanseidel/IAMDinosaur#50]
I got the program to run on Ubuntu. It opens, detects the game, I press "s" then it brings chrome to focus and the Dino runs. The Dino hits the cactus but the program does not recognise this. It just sits on the game over screen. Even in the terminal "GameStatus: PLAYING". It does not change to "OVER". Help would be appreciated : /

**Comment by zixia** [comment]
Yes, I also have this issue.

After looking the code, it seems the following code `gameOverOffset` is not right anymore:
```js
// Read Game state
// (If game is ended or is playing)
GameManipulator.readGameState = function () {
  // Read GameOver
  var found = Scanner.scanUntil(
    [
      GameManipulator.offset[0] + GameManipulator.gameOverOffset[0],
      GameManipulator.offset[1] + GameManipulator.gameOverOffset[1]
    ],

    [2, 0], COLOR_DINOSAUR, false, 20
  );
```

I guess it's because the position of the __GAME OVER__ is changed in the new version of Chrome?

My system is:
* Ubuntu 17.04
* Chrome 59.0.3071.86 (Official Build) (64-bit)

**Comment by zixia** [comment]
@GritPixel I changed 

```diff
--- a/GameManipulator.js
+++ b/GameManipulator.js
@@ -28,8 +28,9 @@ var GameManipulator = {
   gamestate: 'OVER',
 
   // GameOver Position
-  gameOverOffset: [190, -82],
+  gameOverOffset: [197, -74], 
```

The above change fixes this issue for me.

Will send a PR later to make it compatible with different Chrome Browsers.

**Comment by babahooja** [comment]
Sir, I had to change back the coordinates to [190, -82] for it to work for me. I am on a mac, and maybe this is system dependent. Great job with this though.
