### ISSUE TITLE
Auto start new game

### ISSUE THREAD

**Issue by qWici** [ivanseidel/IAMDinosaur#53]
When game is end:
GameStatus all time is "PLAYING"
Dont start new game

Chrome version - Version 59.0.3071.109 (Official Build) (64-bit)
OS - Ubuntu 16.04
Screen Width - 928px

**Comment by babahooja** [comment]
You need to change the gameOverOffset to [190, -82].

**Comment by Gurmindermultani** [comment]
I was able to restart the game by using runner instance api : 
setInterval(function(){ if(Runner.instance_.playing === false){ Runner.instance_.restart() } },1000)

There is one problem, I don't think the Dino is learning, might need some code change.
