### ISSUE TITLE
FAILED TO FIND GAME! on Ubuntu 17.10

### ISSUE THREAD

**Issue by SuuSoJeat** [ivanseidel/IAMDinosaur#67]
Invalid MIT-MAGIC-COOKIE-1 keyFAILED TO FIND GAME!``
![screenshot from 2018-02-07 12-11-10](https://user-images.githubusercontent.com/33922418/35899627-04c8d594-0c00-11e8-984a-5c0346ef65b1.png)

**Comment by jwjohns** [comment]
I get the same

**Comment by ahsanatha** [comment]
same here

**Comment by chipytux** [comment]
same here

**Comment by ctcruz** [comment]
I found the solution!
This warning message is shown cause the screen is much large and the script have a limitation of scaned pixels.
Resize the browser window and execute it again.
![screenshot from 2018-05-08 01-43-46](https://user-images.githubusercontent.com/15198240/39738492-d0c6212c-5261-11e8-8567-7ebae70edcf3.png)

**Comment by dario-bandeira** [comment]
In my case it just worked when I made some changes:

1. **line 10** on _GameManipulator.js_ from
`var COLOR_DINOSAUR = '535353';`
to 
`var COLOR_DINOSAUR = '545454';`
but dino color really is '535353', so I don't know why

2. **line 142** on _GameManipulator.js_ from
`GameManipulator.offset[1] + GameManipulator.gameOverOffset[1]`
to
`GameManipulator.offset[1] + GameManipulator.gameOverOffset[1] - 10`
cause the 'game over' reader was reading a little under the word 'game' and not founding it.

_I'm using Chrome on Ubuntu 18.04_
