### ISSUE TITLE
Credits to IAMDinosaur

### ISSUE THREAD

**Issue by tngan** [ivanseidel/IAMDinosaur#9]
I am really appreciated that @ivanseidel has mentioned the credit.

I have also created a browser-only version [(here)](https://github.com/tngan/g-dino) with different approaches. Please feel free to folk and create an issue.

**Comment by ivanseidel** [comment]
You are welcome! thanks for sharing @tngan =D

Let's talk on how to "merge" both ideas?

**Comment by tngan** [comment]
@ivanseidel Sure =], actually the goal of the original idea is to build a model that everyone can apply their own algorithms to train their dino. See the [growth plan of dino](https://github.com/tngan/g-dino#growth-plan-for-the-little-dino)
